// Generated by CoffeeScript 1.10.0
(function() {
  (function($, _) {
    var debounce, identity, xform, xforms;
    debounce = function(wait, immediateOrFn, fn) {
      var immediate;
      if (fn != null) {
        immediate = immediateOrFn;
      } else {
        fn = immediateOrFn;
        immediate = void 0;
      }
      return _.debounce(fn, wait, immediate);
    };
    if (window.localStorage == null) {
      window.localStorage = {};
    }
    identity = function(input) {
      return input;
    };
    xforms = {
      '#upper': function(input) {
        return input.toUpperCase();
      },
      '#lower': function(input) {
        return input.toLowerCase();
      },
      '#identity': identity
    };
    xform = identity;
    return $(function() {
      var $input, $output;
      $input = $('.input-field .field-textarea');
      $output = $('.output-field .field-textarea');
      $(window).on('hashchange', function() {
        if (xforms[location.hash] != null) {
          xform = xforms[location.hash];
        } else {
          location.hash = '#identity';
        }
        $('.xform-mode-link').each(function(i, e) {
          $(e).removeClass('xform-mode-link-active');
          if (e.href === location.href) {
            return $(e).addClass('xform-mode-link-active');
          }
        });
        return $input.trigger('change');
      });
      $input.on('keyup keypress change', debounce(10, function() {
        localStorage[location.href.split('#')[0]] = $input.val();
        return $output.val(xform($input.val()));
      }));
      $output.on('focus', debounce(0, function() {
        return $output.select();
      }));
      $('.last-input').on('focus', function() {
        return $input.focus();
      });
      $input.val(localStorage[location.href.split('#')[0]]);
      return $(window).trigger('hashchange');
    });
  })($, _);

}).call(this);

//# sourceMappingURL=index.js.map
